"""
📊 Report Generator Module
Formats audit findings into text and HTML reports.
"""
 
from datetime import datetime
 
 
SEVERITY_ORDER = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
STATUS_ICONS   = {"PASS": "✔", "FAIL": "✘", "WARN": "⚠", "SKIP": "—", "INFO": "ℹ"}
HTML_COLORS    = {
    "HIGH":   "#e53e3e",
    "MEDIUM": "#dd6b20",
    "LOW":    "#38a169",
    "INFO":   "#3182ce",
}
 
 
class ReportGenerator:
 
    def __init__(self, findings: dict):
        self.meta     = findings.get("metadata", {})
        self.security = findings.get("security", [])
        self.compliance = findings.get("compliance", [])
        self.network  = findings.get("network", [])
        self.all      = self.security + self.compliance + self.network
 
    def _count_by_severity(self):
        counts = {"HIGH": 0, "MEDIUM": 0, "LOW": 0}
        for f in self.all:
            if f["status"] in ("FAIL", "WARN"):
                sev = f.get("severity", "LOW")
                counts[sev] = counts.get(sev, 0) + 1
        return counts
 
    def _count_by_status(self):
        counts = {"PASS": 0, "FAIL": 0, "WARN": 0, "SKIP": 0}
        for f in self.all:
            s = f.get("status", "SKIP")
            counts[s] = counts.get(s, 0) + 1
        return counts
 
    # ── Text Report ────────────────────────────────────────────────
    def generate_text(self):
        lines = []
        SEP = "=" * 62
 
        lines.append(SEP)
        lines.append("  SYSTEM AUDIT REPORT")
        lines.append(SEP)
        lines.append(f"  Host      : {self.meta.get('hostname', 'N/A')}")
        lines.append(f"  Date/Time : {self.meta.get('timestamp', 'N/A')}")
        lines.append(f"  Target    : {self.meta.get('target', 'localhost')}")
        lines.append(SEP)
 
        for section, items in [
            ("🔐 SECURITY AUDIT", self.security),
            ("📏 COMPLIANCE CHECKS", self.compliance),
            ("🌐 NETWORK AUDIT", self.network),
        ]:
            if not items:
                continue
            lines.append(f"\n[{section}]")
            lines.append("-" * 62)
            for f in sorted(items, key=lambda x: SEVERITY_ORDER.get(x.get("severity","LOW"), 2)):
                icon   = STATUS_ICONS.get(f["status"], "?")
                sev    = f.get("severity", "LOW")
                check  = f.get("check", "Unknown")
                detail = f.get("detail", "")
                rec    = f.get("recommendation", "")
                status = f.get("status", "")
 
                lines.append(f"\n  [{sev}] {icon} {status} — {check}")
                lines.append(f"         {detail}")
                if rec and rec != "None":
                    lines.append(f"         → Recommendation: {rec}")
 
        # Summary
        severity_counts = self._count_by_severity()
        status_counts   = self._count_by_status()
        lines.append(f"\n{SEP}")
        lines.append("  SUMMARY")
        lines.append(SEP)
        lines.append(f"  Total Checks : {len(self.all)}")
        lines.append(f"  PASS         : {status_counts['PASS']}")
        lines.append(f"  FAIL         : {status_counts['FAIL']}")
        lines.append(f"  WARN         : {status_counts['WARN']}")
        lines.append(f"  SKIP         : {status_counts['SKIP']}")
        lines.append("")
        lines.append(f"  ⚠ High Severity Issues   : {severity_counts['HIGH']}")
        lines.append(f"  ⚠ Medium Severity Issues : {severity_counts['MEDIUM']}")
        lines.append(f"  ✔ Low / Info              : {severity_counts['LOW']}")
        lines.append(SEP)
 
        # Risk assessment
        high = severity_counts["HIGH"]
        if high == 0:
            risk_msg = "✔ OVERALL RISK: LOW — System appears well-hardened."
        elif high <= 2:
            risk_msg = "⚠ OVERALL RISK: MEDIUM — Address HIGH findings promptly."
        else:
            risk_msg = "✘ OVERALL RISK: HIGH — Immediate remediation required!"
        lines.append(f"  {risk_msg}")
        lines.append(SEP)
        lines.append("  Generated by: Unified Audit Tool for Ubuntu")
        lines.append(SEP)
        return "\n".join(lines)
 
    # ── HTML Report ────────────────────────────────────────────────
    def generate_html(self):
        severity_counts = self._count_by_severity()
        status_counts   = self._count_by_status()
        high = severity_counts["HIGH"]
        risk_color = "#e53e3e" if high > 2 else ("#dd6b20" if high > 0 else "#38a169")
        risk_label = "HIGH" if high > 2 else ("MEDIUM" if high > 0 else "LOW")
 
        rows = ""
        for section, items in [
            ("Security", self.security),
            ("Compliance", self.compliance),
            ("Network", self.network),
        ]:
            for f in sorted(items, key=lambda x: SEVERITY_ORDER.get(x.get("severity","LOW"), 2)):
                sev    = f.get("severity", "LOW")
                status = f.get("status", "?")
                color  = HTML_COLORS.get(sev, "#718096")
                s_bg   = {"PASS":"#c6f6d5","FAIL":"#fed7d7","WARN":"#feebc8","SKIP":"#e2e8f0","INFO":"#bee3f8"}
                rows += f"""
                <tr>
                  <td><span style='background:{color};color:#fff;padding:2px 8px;border-radius:4px;font-size:12px'>{sev}</span></td>
                  <td><span style='background:{s_bg.get(status,"#e2e8f0")};padding:2px 8px;border-radius:4px;font-size:12px'>{status}</span></td>
                  <td>{section}</td>
                  <td>{f.get('check','')}</td>
                  <td>{f.get('detail','')}</td>
                  <td style='color:#2b6cb0'>{f.get('recommendation','')}</td>
                </tr>"""
 
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>System Audit Report</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f7fafc; color: #2d3748; }}
  .header {{ background: #1a202c; color: #fff; padding: 32px; }}
  .header h1 {{ font-size: 24px; margin-bottom: 8px; }}
  .header p  {{ color: #a0aec0; font-size: 14px; }}
  .stats {{ display: flex; gap: 16px; padding: 24px; flex-wrap: wrap; }}
  .stat-card {{ background: #fff; border-radius: 8px; padding: 20px 28px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); min-width: 140px; }}
  .stat-card .num {{ font-size: 36px; font-weight: 700; }}
  .stat-card .lbl {{ font-size: 13px; color: #718096; margin-top: 4px; }}
  .risk-banner {{ margin: 0 24px 24px; padding: 16px 24px; background: {risk_color}; color: #fff;
                  border-radius: 8px; font-size: 16px; font-weight: 600; }}
  .container {{ padding: 0 24px 40px; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff;
           border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
  th {{ background: #2d3748; color: #fff; padding: 12px 16px; text-align: left; font-size: 13px; }}
  td {{ padding: 12px 16px; border-bottom: 1px solid #e2e8f0; font-size: 13px; vertical-align: top; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover td {{ background: #f7fafc; }}
  .footer {{ text-align: center; padding: 24px; color: #a0aec0; font-size: 12px; }}
</style>
</head>
<body>
<div class="header">
  <h1>🔐 System Audit Report</h1>
  <p>Host: <strong>{self.meta.get('hostname','N/A')}</strong> &nbsp;|&nbsp;
     Date: {self.meta.get('timestamp','N/A')} &nbsp;|&nbsp;
     Target: {self.meta.get('target','localhost')}</p>
</div>
 
<div class="stats">
  <div class="stat-card"><div class="num">{len(self.all)}</div><div class="lbl">Total Checks</div></div>
  <div class="stat-card"><div class="num" style="color:#38a169">{status_counts['PASS']}</div><div class="lbl">Passed</div></div>
  <div class="stat-card"><div class="num" style="color:#e53e3e">{status_counts['FAIL']}</div><div class="lbl">Failed</div></div>
  <div class="stat-card"><div class="num" style="color:#dd6b20">{status_counts['WARN']}</div><div class="lbl">Warnings</div></div>
  <div class="stat-card"><div class="num" style="color:#e53e3e">{severity_counts['HIGH']}</div><div class="lbl">High Severity</div></div>
  <div class="stat-card"><div class="num" style="color:#dd6b20">{severity_counts['MEDIUM']}</div><div class="lbl">Medium Severity</div></div>
</div>
 
<div class="risk-banner">⚠ Overall Risk Level: {risk_label}</div>
 
<div class="container">
<table>
  <thead>
    <tr>
      <th>Severity</th><th>Status</th><th>Module</th>
      <th>Check</th><th>Detail</th><th>Recommendation</th>
    </tr>
  </thead>
  <tbody>
    {rows}
  </tbody>
</table>
</div>
 
<div class="footer">
  Generated by Unified Security, Compliance & Network Audit Tool for Ubuntu &nbsp;|&nbsp;
  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
</div>
</body>
</html>"""
